In [117]:
import numpy as np
arr = [[12, 14, 13],[ 0,  4, 12],[10,  7,  0]]
arr

[[12, 14, 13], [0, 4, 12], [10, 7, 0]]

In [118]:
def multiplicative_inverse(e):
    for i in range(1,e+1):
        mod = (i*e)%26
        if mod == 1:
            break
    return i
det = np.linalg.det(arr)
inv = multiplicative_inverse(int(det)%26)
inv

22

In [119]:
cof = np.linalg.inv(arr) * det
cof  = np.rint(cof)
# cof = cof.astype(int)%26
cof

array([[ -84.,   91.,  116.],
       [ 120., -130., -144.],
       [ -40.,   56.,   48.]])

In [115]:
A_inverse = (inv*cof)%26

In [34]:
def find_inverse(arr):
    det = np.linalg.det(arr)
    inv = multiplicative_inverse(int(det)%26)
    cof = np.linalg.inv(arr) * det
    cof  = np.rint(cof)
    cof = cof.astype(int)%26
    return (inv*cof)%26

In [35]:
find_inverse(arr)

array([[ 4,  9, 15],
       [15, 17,  6],
       [24,  0, 17]], dtype=int32)

In [39]:
msg = [15,0,24]
ci = np.dot(msg,arr)%26
ci

array([17, 17, 11], dtype=int32)

In [42]:
pl = np.dot(ci,find_inverse(arr))%26
pl

array([15,  0, 24], dtype=int32)

In [57]:
n = 3
arr = np.zeros((3,3)).astype(int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
key = input('Enter Key : ')
while(len(key) != n*n):
    key = input('Enter Key again : ')

Enter Key : rrfvsvcct


In [74]:
k = 0
for i in range(n):
    for j in range(n):
        arr[i][j] = ord(key[k])-97
        k = k+1
arr

array([[17, 17,  5],
       [21, 18, 21],
       [ 2,  2, 19]])

In [95]:
msg = 'pay'
if len(msg)%n !=0:
    for i in range(n-(len(msg)%n)):
        msg = msg+'x'
msg

'pay'

In [103]:
def encryption(msg,arr):
    cipher = ''
    for i in range(0,len(msg),3):
        c1 = ord(msg[i])-97
        c2 = ord(msg[i+1])-97
        c3 = ord(msg[i+2])-97
        msg_arr = [c1,c2,c3]
        ci = np.dot(msg_arr,arr)%26
        for j in ci:
            cipher = cipher+ chr(j+97)
    return cipher
c = encryption(msg,arr)
c

'rrl'

In [107]:
def decryption(msg,arr):
    plain = ''
    for i in range(0,len(msg),3):
        p1 = ord(msg[i])-97
        p2 = ord(msg[i+1])-97
        p3 = ord(msg[i+2])-97
        msg_arr = [p1,p2,p3]
        pl = np.dot(msg_arr,find_inverse(arr))%26
        for j in pl:
            plain = plain+ chr(j+97)
    return plain
p = decryption(c,arr)
p

'pay'